export default {
  app: null,
  startTime: null,
  employee: null,
  store: '',
  date: new Date().toISOString().substr(0, 10),
  customerName: '',
  address: '',
  city: '',
  postcode: '',
  phone: '',
  email: '',
  venue: '',
  weddingDate: '',
  foundUs: [],
  budget: [],
  bridesmaids: '',
  flowergirls: '',
  partnersName: ''
}